config/routes.rb
Rails.application.routes.draw do
	resources :posts
	devise_for :users, path: 'auth',
						 path_names: {
								 sign_in: 'login',
								 sign_out: 'logout',
								 password: 'secret',
								 confirmation: 'verification',
								 unlock: 'unblock',
								 registration: 'register',
								 sign_up: 'sign_up'
						 }
	root 'welcome#index'
	get 'demo', to: 'welcome#login'
	get 'about', to: 'welcome#about'
	get 'explore', to: 'welcome#not-ready'

	# ROUTES for API
	# core
	namespace :core	do
		namespace :v1 do
			resources :Posts , :controller => 'posts'
		end
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  # TODO Add the missing.png file to assets
  validates :post_image, presence: true
  has_attached_file :post_image, styles: { large: "1920x1080>", medium: "612x612>", thumb: "161x161>" } #default_url: "/images/:style/missing.png"
  validates_attachment_content_type :post_image, content_type: /\Aimage\/.*\z/

  scope :NewestFirst, lambda { order("posts.created_at DESC") }
end

app/models/user.rb
class User < ApplicationRecord
  # Only allow letter, number, underscore and punctuation.
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  # To validate username
  # For example, if my username is equal to your email I'm not
  # allowed to choose this username as my username and that means the username must be unique.
  # However, note that relying ONLY on this second validation still allows a user to choose someone
  # else's valid email address as a username, as long as that email is not yet associated with an
  # account. This should therefore be used only as a backup validation.
  validate :validate_username

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable, :timeoutable

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    demo_path
  end

  protected

  def configure_permitted_parameters
    added_attrs_sign_up = [:username, :email, :password, :password_confirmation, :phone_number , :remember_me]
    added_attrs_account_update = [:username, :email, :password ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs_sign_up
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs_account_update
  end
end

app/controllers/core/v1/posts_controller.rb
class Core::V1::PostsController < ApplicationController

	#GET /core/v1/Posts
	def index
		@posts = Post.NewestFirst
		render json: @posts, status: :ok
	end

	def show
		render json: @post
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			render json: @post, status: :created
		else
			render json: @post.errors, status: :unprocessable_entity
		end
	end

	def update
		@post = Post.find(params[:id])
		if @post.update_attributes(post_params)
			render json: @post
		else
			render json: @post.errors, status: :unprocessable_entity
		end
	end

	def destroy
		@post = Post.where(id: params[:id]).first
		if @post.destroy
			head(:ok)
		else
			head(:unprocessable_entity)
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_post
		@post = Post.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def post_params
		params.require(:post).permit(:caption, :post_image)
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]

	# GET /posts
	# GET /posts.json
	def index
		@posts = Post.all
	end

	# GET /posts/1
	# GET /posts/1.json
	def show
	end

	# GET /posts/new
	def new
		@post = Post.new
	end

	# GET /posts/1/edit
	def edit
	end

	# POST /posts
	# POST /posts.json
	def create
		@post = Post.new(post_params)

		respond_to do |format|
			if @post.save
				format.html { redirect_to @post, notice: 'Post was successfully created.' }
				format.json { render :show, status: :created, location: @post }
			else
				format.html { render :new }
				format.json { render json: @post.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /posts/1
	# PATCH/PUT /posts/1.json
	def update
		respond_to do |format|
			if @post.update(post_params)
				format.html { redirect_to @post, notice: 'Post was successfully updated.' }
				format.json { render :show, status: :ok, location: @post }
			else
				format.html { render :edit }
				format.json { render json: @post.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /posts/1
	# DELETE /posts/1.json
	def destroy
		@post.destroy
		respond_to do |format|
			format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_post
		@post = Post.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def post_params
		params.require(:post).permit(:caption, :post_image)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def login
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/core/v1/posts_helper.rb
module Core::V1::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LifeAppliance</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Favicons -->
    <%= favicon_link_tag('logo/apple-icon-57x57.png' , rel:'apple-touch-icon' , sizes: '57x57') %>
    <%= favicon_link_tag('logo/apple-icon-60x60.png' , rel:'apple-touch-icon' , sizes: '60x60') %>
    <%= favicon_link_tag('logo/apple-icon-72x72.png' , rel:'apple-touch-icon' , sizes: '72x72') %>
    <%= favicon_link_tag('logo/apple-icon-76x76.png' , rel:'apple-touch-icon' , sizes: '76x76') %>
    <%= favicon_link_tag('logo/apple-icon-114x114.png' , rel:'apple-touch-icon' , sizes: '114x114') %>
    <%= favicon_link_tag('logo/apple-icon-120x120.png' , rel:'apple-touch-icon' , sizes: '120x120') %>
    <%= favicon_link_tag('logo/apple-icon-144x144.png' , rel:'apple-touch-icon' , sizes: '144x144') %>
    <%= favicon_link_tag('logo/apple-icon-152x152.png' , rel:'apple-touch-icon' , sizes: '152x152') %>
    <%= favicon_link_tag('logo/apple-icon-180x180.png' , rel:'apple-touch-icon' , sizes: '180x180') %>
    <%= favicon_link_tag('logo/android-icon-192x192.png' , rel:'icon' , sizes:'192x192' , type:'image/png') %>
    <%= favicon_link_tag('logo/android-icon-96x96.png' , rel:'icon' , sizes:'96x96' , type:'image/png') %>
    <!-- End -->

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with url:posts_path, html: { multipart: true } do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :caption %>
    <%= form.text_field :caption, id: :post_caption %>
  </div>

		<div>
			<%= form.file_field :avatar %>
		</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<!-- todo is most fix -->

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= form_for @post, url: posts_path, html: { multipart: true } do |form| %>
		<%= form.text_field :caption %>
		<%= form.file_field :post_image %>
		<%= form.submit %>
<% end %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Caption</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.caption %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for @post, url: posts_path, html: { multipart: true } do |form| %>
		<%= form.text_field :caption %>
		<%= form.file_field :post_image %>
		<%= form.submit %>
<% end %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Caption:</strong>
  <%= @post.caption %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/about.html.erb
<div class="layout">
  <div class="left-page">
    <div class="app-container">
      <h1 class="title">
        What is LifeAppliance?
      </h1>
      <h2 class="subtitle">
        Life appliance is the next level of your user experience on your social media.
      </h2>
      <h2 class="title">How?</h2>
      <h3 class="subtitle">
        By creating a platform that can put all your social media contents in one place or one app.
      </h3>
    </div>
  </div>
  <div class="right-page about-page-image" id="treeLeaves">
    <div class="app-container">
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<section class="hero is-fullheight">

  <div class="header">
    <header class="nav">
      <div class="container">
        <div class="nav-left">
          <a href="#" class="nav-item">
            <%= image_tag("logo/android-icon-96x96.png" , class: 'logo') %>
          </a>
        </div>
        <span class="nav-toggle">
          <span>Home</span>
          <span>About us</span>
          <span>Explore</span>
        </span>
        <div class="nav-right nav-menu">
          <%= link_to('Home', root_path , :class => 'nav-item is-active') %>
          <%= link_to('About us', about_path , :class => 'nav-item') %>
          <%= link_to('Explore', explore_path , :class => 'nav-item') %>
          <span class="nav-item">
            <%= link_to("Sign in", new_user_session_url ,class:'button is-success is-inverted') %>
          </span>
          <span class="nav-item">
            <%= link_to("Sign up", new_user_registration_url ,class:'button is-success is-inverted') %>
          </span>
        </div>
      </div>
    </header>
    <div class="content"></div>
    <div class="background-gradient"></div>
  </div>
</section>

app/views/welcome/login.html.erb
<div class="header">
<header class="nav">
  <div class="container">
    <div class="nav-left">
      <a href="#" class="nav-item">
        <%= image_tag("logo/android-icon-96x96.png" , class: 'logo') %>
      </a>
    </div>
      <% if user_signed_in? %>
          <span class="nav-item">
            <%= link_to('Logout', destroy_user_session_path, method: :delete ,class:'button is-success') %>
          </span>
      <% else %>
          <span class="nav-item">
                <%= link_to("Sign in", new_user_session_url ,class:'button is-success is-inverted') %>
          </span>
          <span class="nav-item">
                <%= link_to("Sign up", new_user_registration_url ,class:'button is-success is-inverted') %>
          </span>
      <% end %>
    </div>
  </div>
</header>
  <div class="card demo">
    <div class="card-content">
      <p class="title">
        please logout the system is on developer-mode and won't respond to you as soon that system is back we are going to notify your via email.
      </p>
    </div>
  </div>
</div>

app/views/welcome/not-ready.html.erb
<section class="hero is-danger is-bold is-fullheight">
  <div class="hero-body">
    <div class="app-container">
      <h1 class="title">
        Ops!!404
      </h1>
      <h2 class="subtitle">
        The server has not found anything matching the Request
      </h2>
    </div>
  </div>
</section>

app/views/wellcome/index.html.erb
<section class="hero is-fullheight">

  <div class="header">
    <header class="nav">
      <div class="container">
        <div class="nav-left">
          <a href="#" class="nav-item">
            <%= image_tag("logo/android-icon-96x96.png" , class: 'logo') %>
          </a>
        </div>
        <span class="nav-toggle">
          <span></span>
          <span></span>
          <span></span>
        </span>
        <div class="nav-right nav-menu">
          <a class="nav-item is-active">
            Home
          </a>
          <a class="nav-item">
            About us
          </a>
          <a class="nav-item">
            Explore
          </a>
          <span class="nav-item">
            <a class="button is-success is-inverted">
              <span>Sign in</span>
            </a>
          </span>
          <span class="nav-item">
            <a class="button is-primary is-inverted">
              <span>Sign up</span>
            </a>
          </span>
        </div>
      </div>
    </header>
    <div class="content"></div>
    <div class="background-gradient"></div>
  </div>
</section>